# Generated by Django 4.2.1 on 2023-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orders_order_date_alter_orders_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
